<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <script src="../lib/promise.js"></script>
  <script>
    // var a = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve(111);
    //   }, 1000);
    // })
    // a.then(function(res) {
    //   console.log(res);
    //   var bbb = new Promise((resolve, reject) => {
    //     reject(222 + res);
    //   })
    //   return bbb;
    // }).catch(err => console.log(err));

    // console.log(a);
    // var a = {
    //   b: 1,
    //   then: function() {
    //     console.log(this.b);
    //   }
    // }
    // const p3 = new Promise(function (resolve, reject) {
    //   setTimeout(() => resolve(a), 1000)
    // })

    // p3
    //   .then(result => console.log(result))
    //   .catch(error => console.log(error))
    // const p1 = new Promise(function (resolve, reject) {
    //   setTimeout(() => reject(new Error('fail')), 3000)
    // })

    // const p2 = new Promise(function (resolve, reject) {
    //   setTimeout(() => resolve(p1), 1000)
    // })

    // p2
    //   .then(result => console.log(result))
    //   .catch(error => console.log(error))
  </script>
  <script>
    /* eslint-disable */
    // var a = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     console.log(111)
    //     resolve(111)
    //   }, 1000)
    // })
    // var b = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     console.log(222)
    //     reject(333)
    //   }, 1500)
    // })
    // var c = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     console.log(444)
    //     reject(555)
    //   }, 2500)
    // })

    // Promise.race([a, b, c]).then(res => console.log(res), err => console.log(err))
    // Promise.all('1234').then(res => console.log(res))
    // Promise.reject(2).then(res => console.log(res)).catch(err => console.log('err ' + err))
    
    // 同一个promise的多个调用栈
    // var promise = new Promise(resolve => resolve(111))
    // promise.then(function(res) {console.log('then1: ' + res)})
    // promise.then(function(res) {console.log('then2: ' + res)})

    // then参数不为函数时忽略该then
    // var promise = new Promise((resolve,reject) => {resolve(111)})
    // promise.then(111).then(res => console.log(res))

    // 测试onFulfilled与onRejected, 如果返回promise则会改变父promise状态，否则只有报错的情况下才会调用reject
    var promise = new Promise((resolve,reject) => {reject(111)})
    promise.then(res => {
      console.log('resolve: ' + res)
      return res
    }, err => {
      console.log('reject: ' + err)
      return err
    }).then(res => console.log('then: ' + res))
    .catch(err => console.log('catch: ' + err))
    
  </script>
</body>

</html>